version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network
    restart: always
  spring-boot:
    container_name: nanal-server
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - db_network
networks:
  db_network:
    driver: bridge